# Basically a stripped down version of matrix-org's synapse tests.yml file. We're only interested in Complement here,
# as Sytest and the unit tests are not our concern. Nothing we do in this repo should affect those not working in any
# way. Test against develop, as the most leading edge.
name: Tests

on:
  push:
    paths-ignore:
      - "release-versions/**"
      - "README.md"
  pull_request:
    types:
      - opened
      - edit
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  complement:
    if: "${{ !failure() && !cancelled() }}"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - arrangement: monolith
            database: SQLite

          - arrangement: monolith
            database: Postgres

          - arrangement: workers
            database: Postgres

          - arrangement: workers
            database: Postgres
            worker_types: 'event_persister:2, stream_writers=account_data+presence+receipts+to_device+typing, singles=background_worker+user_dir+frontend_proxy+media_repository+appservice, senders=pusher+federation_sender, readers=federation_reader+client_reader+synchrotron+federation_inbound+event_creator:2'

          - arrangement: monolith
            database: SQLite
            unix_sockets: True

          - arrangement: monolith
            database: Postgres
            unix_sockets: True

          - arrangement: workers
            database: Postgres
            unix_sockets: True

          - arrangement: workers
            database: Postgres
            worker_types: 'event_persister:2, stream_writers=account_data+presence+receipts+to_device+typing, singles=background_worker+user_dir+frontend_proxy+media_repository+appservice, senders=pusher+federation_sender, readers=federation_reader+client_reader+synchrotron+federation_inbound+event_creator:2'
            unix_sockets: True

          - arrangement: monolith
            database: SQLite
            reactor: asyncio

          - arrangement: monolith
            database: Postgres
            reactor: asyncio

          - arrangement: workers
            database: Postgres
            reactor: asyncio

          - arrangement: workers
            database: Postgres
            reactor: asyncio
            worker_types: 'event_persister:2, stream_writers=account_data+presence+receipts+to_device+typing, singles=background_worker+user_dir+frontend_proxy+media_repository+appservice, senders=pusher+federation_sender, readers=federation_reader+client_reader+synchrotron+federation_inbound+event_creator:2'

          - arrangement: monolith
            database: SQLite
            reactor: asyncio
            unix_sockets: True

          - arrangement: monolith
            database: Postgres
            reactor: asyncio
            unix_sockets: True

          - arrangement: workers
            database: Postgres
            reactor: asyncio
            unix_sockets: True

          - arrangement: workers
            database: Postgres
            reactor: asyncio
            worker_types: 'event_persister:2, stream_writers=account_data+presence+receipts+to_device+typing, singles=background_worker+user_dir+frontend_proxy+media_repository+appservice, senders=pusher+federation_sender, readers=federation_reader+client_reader+synchrotron+federation_inbound+event_creator:2'
            unix_sockets: True


    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          path: synapse-workers

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Setup Go
        uses: actions/setup-go@v4

      - name: Prepare Complement's Prerequisites
        if: ${{ !cancelled() }}
        run: synapse-workers/.ci/scripts/setup_complement_prerequisites.sh

      - name: Run Complement Tests
        if: ${{ !cancelled() }}
        shell: bash
        env:
          POSTGRES: ${{ (matrix.database == 'Postgres') && 1 || '' }}
          WORKERS: ${{ (matrix.arrangement == 'workers') && 1 || '' }}
          WORKER_TYPES: ${{ matrix.worker_types || '' }}
          # Take advantage of the fact that the validation for truthy doesn't actually exist here.
          ASYNCIO_REACTOR: ${{ matrix.reactor || '' }}
          UNIX_SOCKETS: ${{ (matrix.unix_sockets) && 1 || '' }}
        run: |
          set -o pipefail
          COMPLEMENT_DIR=`pwd`/complement synapse-workers/.ci/scripts/complement.sh -json 2>&1 | synapse-workers/.ci/scripts/gotestfmt

  # a job which marks all the other jobs as complete
  tests-done:
    if: ${{ always() }}
    needs:
      - complement
    runs-on: ubuntu-22.04
    steps:
      - uses: matrix-org/done-action@v2
        with:
          needs: ${{ toJSON(needs) }}
